### ISSUE TITLE
Support Volcano scheduler in Spark community

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#1704]
#### What would you like to be added:
Volcano already integrated with spark-operator to support runing spark on Kubernetes with Volcano.
We are also going to support volcano schedulers in Spark community.  This issue is used to track the overall progress.
ref:  https://issues.apache.org/jira/browse/SPARK-36057

Sub Tasks
- [x] spark part
      https://issues.apache.org/jira/browse/SPARK-36057
- [x] Add mirror for Spark voclano IT #2163 
- [x] Add E2E Spark Integration Test #2113 
- [x] Change volcano docker release time to 2 times per day #2071
- [x] dd Volcano log collect in Spark IT #2205 
- [x] Add multiarch support for base image #2142

**Comment by Yikun** [comment]
Yes, cute bot, we are still working on it.
