### ISSUE TITLE
Enhance Volcano to repalce kube-scheduler smoothly

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#2394]
#### What would you like to be added:
Use Volcano to replace kube-scheduler to scheduling both batch workload and service type workload in the same cluster.  
- allow specify multiple scheduler names in command line. e.g. `default-scheduler` , `volcano`
- users whoever using kube-scheduler or volcano can be migrated to volcano smoothly.

#### Why is this needed:
Currently, users  user kube-scheduler and volcano in the same cluster which cause high maintainnence effort. They want to use volcano to scheduler all kinds of workload.

sub-tasks
- [x] support volumeBinding plugin([#2485](https://github.com/volcano-sh/volcano/issues/2485))
- [x] support volumeZone plugin([#2479](https://github.com/volcano-sh/volcano/issues/2479))
- [x] add podTopologySpread plugin([#2514](https://github.com/volcano-sh/volcano/issues/2514))
- [x] add selector spread plugin([#2500](https://github.com/volcano-sh/volcano/issues/2500))
- [x] add nodeVolumeLimits([#2458](https://github.com/volcano-sh/volcano/issues/2458))

**Comment by kerthcet** [comment]
A little confused here, we do added selector spread plugin(https://github.com/volcano-sh/volcano/issues/2500) but I can't find it in the code base or PRs removed this plugin. Can you give me a light? @william-wang
