### ISSUE TITLE
Theme of next release

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#244]
Volcano'd like to have another release around end of Aug; there're the proposed features that maybe included in next release, please share your comments/suggestion and if any other requirements, please also feel free to share :)

## Job Management

- [x] Delay pod creation improvement (https://github.com/volcano-sh/volcano/issues/135) (@wangyuqing4)

## Queue Management 

- [x] Lifecycle manage of Queue, e.g. Queue's status (@hzxuzhonghu )
- [ ] Improve Queue CRD (@hzxuzhonghu )

## Scheduler/Policy

- [ ] GPU enhancement (https://github.com/kubernetes-sigs/kube-batch/issues/236) (@TommyLike)
- [ ] Reservation to avoid starvation (https://github.com/volcano-sh/volcano/issues/13) (@sivanzcw)
- [x] Fair-sharing cross namespace (https://github.com/volcano-sh/volcano/issues/147) (@lminzhw)
- [x] Proportion enhancement for Queue, e.g. (https://github.com/kubernetes-sigs/kube-batch/issues/492) (@william-wang)
- [ ] Preemption/Reclaim enhancement (@william-wang)

## Stability

- [x] Improve code coverage of controller & scheduler ( @asifdxtreme )
- [ ] Improve e2e test ( @asifdxtreme )

**Comment by k82cn** [comment]
/cc @hex108 @johnugeorge for Queue
/cc @richardsliu @gaocegege for delay pod creation
/cc @ahmad-diaa  for fair-sharing
/cc @wsxiaozhang @kinglion811 for GPU part

Please feel free to hands up if any items you'd like to contribute :)

/cc @jeefy @Jeffwan @mrbobbytables who may also interest; and please feel free to share your requirements/comments if any :)

**Comment by jeefy** [comment]
No hard reqs yet, but couple thoughts:
- This looks like a lot of work, and it's exciting to think of all this getting rounded out.
- It's awesome if the plan is to get into a semi-regular release cadence.

**Comment by k82cn** [comment]
> It's awesome if the plan is to get into a semi-regular release cadence.

Yes, we'd like to have a minor release every quarter, similar to k8s :)

**Comment by hzxuzhonghu** [comment]
There are also many clean code work after `kube-batch` in tree. 

It mainly focus on:

1. the variable naming, like `kbClient` => `vcClient`

1. duplicate import, like `"volcano.sh/volcano/pkg/client/clientset/versioned"`

**Comment by k82cn** [comment]
> There are also many clean code work after kube-batch in tree.

Let's handle them as bug fix :)

**Comment by Jeffwan** [comment]
It would be great to see some of the feature released by end of Aug. Do we consider to have a quarterly release cycle?

**Comment by hzxuzhonghu** [comment]
>It would be great to see some of the feature released by end of Aug. Do we consider to have a quarterly release cycle?

Both are yes.

**Comment by hzxuzhonghu** [comment]
@wangyuqing4 @TommyLike @william-wang @lminzhw @sivanzcw Can you leave a message about your task status? We plan to release V0.2 by the end of Aug.

**Comment by william-wang** [comment]
@hzxuzhonghu Here is the status from me.
#355 reviewing
#404 writting design doc and test more cases.

**Comment by k82cn** [comment]
please help to move the items to v0.3 if you can not get PRs merged before next Monday :)

ping me if any review required :)

**Comment by TommyLike** [comment]
@hzxuzhonghu Currently I am working on spark-operator support volcano scheduler. So it's not guaranteed that can be merged before the deadline, but I will keep working on this tomorrow.

**Comment by k82cn** [comment]
@TommyLike , please continue the work on spark-operator, it's high priority for now.

**Comment by k82cn** [comment]
@Jeffwan , nop, please open an issue for it.  we can try to have it next release.
