### ISSUE TITLE
PG minresource has some problems after PR#1459

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#2921]
**What happened**:

https://github.com/volcano-sh/volcano/blob/2721275aebfc26ac2c0e8ff4afeda1dbd852061c/pkg/controllers/job/job_controller_actions.go#L782-L796

There are many cases.
- job.MinAvailable !=0,  task.MinAvailable == 0: (job.MinAvailable<=sum(task.Replicas))
  - [x] sum up task's replicas untile pod cnt == job.MinAvailable

- job.MinAvailable ==0, task.MinAvailable == 0: (job.MinAvailable==sum(task.Replicas))
  - [x] sum up task's replicas or empty (Done via patchDefaultMinAvailable func in admission webhook)

- job.MinAvailable ==0, task.MinAvailable != 0: (job.MinAvailable==sum(task.MinAvailable)<=sum(task.Replicas))
  - [x] sum up tasks's MinAvailable(Done via patchDefaultMinAvailable func in admission webhook)
  - [ ] calulate min resource from highest priority role to lowest priority and each role with first min avaiable member

- job.MinAvailable !=0, task.MinAvailable != 0:
     -  job.MinAvailable >= sum(task.MinAvailable)
         - [ ] TODO
     -  job.MinAvailable < sum(task.MinAvailable)
         - [ ] TODO

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hwdef** [comment]
@shinytang6 
Could you please check this?

**Comment by wangyang0616** [comment]
Is it convenient to share the problem and fix pr at the community meeting this week? @lowang-bh

**Comment by renwenlong-github** [comment]
# 1、job.MinAvailable =0
## 1.1、task.MinAvailable == 0
webhook mutate set job.MinAvailable = sum(task.Replacas)
## 1.2、task.MinAvailable != 0
webhook mutate set job.MinAvailable = sum(task.MinAvailable)

# 2、job.MinAvailable !=0
## 2.1、task.MinAvailable == 0
- when task is one is ok, webhook mutate set task.MinAvailable=job.MinAvailable
- when task is multiple， webhook validate job.MinAvailable = sum(task.Replacas). otherwise, I don’t know which tasks is job.MinAvailable
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: minavailable-job
spec:
  schedulerName: volcano
  minAvailable: 4
  tasks:
    - replicas: 5
      minAvailable: 2
      name: "master"
      template:
        metadata:
          name: master
        spec:
          containers:
            - image: nginx
              name: nginx
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
          restartPolicy: OnFailure
    - replicas: 3
      minAvailable: 2
      name: "work"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              name: nginx
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
          restartPolicy: OnFailure
```

## 2.2、task.MinAvailable != 0
user set job.MinAvailable and task.MinAvailable. webhook validate  job.MinAvailable must equal to sum(task.MinAvailable)
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: minavailable-job
spec:
  schedulerName: volcano
  minAvailable: 5
  tasks:
    - replicas: 5
      minAvailable: 2
      name: "master"
      template:
        metadata:
          name: master
        spec:
          containers:
            - image: nginx
              name: nginx
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
          restartPolicy: OnFailure
    - replicas: 3
      minAvailable: 2
      name: "work"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              name: nginx
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
          restartPolicy: OnFailure
```

Who can know job.minAvailable: 5 represents those pods
