### ISSUE TITLE
Queue capacity scheduling

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#3242]
#### What would you like to be added:

Add capacity scheduling capability for queue

#### Why is this needed:
Volcano Proportion plugin provides capacity scheduling and fair scheduling between multiple queues by weight, and the Queue minimal resource (guaranteed resource) and maximal resource (capacity) is supported as well. Users run heterogeneous clusters with varying resource types (i.e. different types of GPU cards and network interfaces, and require Currently the user requirerequires fine-grained resource sharing and preemption between queues, and it is expected to configure the `deserved resource` using resourceType scalar rather than `weight` (a simple percentage of cluster resource) for each queue. 

#### Task list
- [x] Add scheduling design doc. https://github.com/volcano-sh/volcano/pull/3277
- [x] API change in https://github.com/volcano-sh/apis https://github.com/volcano-sh/apis/pull/121
- [x] capacity scheduling implementation in this repo. https://github.com/volcano-sh/volcano/pull/3283

**Comment by Monokaix** [comment]
All have done!
