### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#3502]
#### What would you like to be added:
Optimize the controllers and schedulers components to improve the performence from end to end for high performance workload.

#### Why is this needed:
More and more workloads are being migrated to Kubernetes on Volcano,  Some workloads have higher requirements for high throughput and low latency, e.g bilibili requires best qps for vedio transcoding from job created to pod running.

Some community users are migrating high performace workload

**Comment by Monokaix** [comment]
Controller related:

- [ ] https://github.com/volcano-sh/volcano/issues/3490
- [ ] https://github.com/volcano-sh/volcano/issues/3485
- [ ] https://github.com/volcano-sh/volcano/issues/3484
- [ ] https://github.com/volcano-sh/volcano/issues/3488

**Comment by lowang-bh** [comment]
Scheduler related:

issues:

- [ ]  [It's better to check and skip allocation for job when it is poped #3047](https://github.com/volcano-sh/volcano/issues/3047)
- [ ] [cache feasible nodes for a job's tasks #3492](https://github.com/volcano-sh/volcano/issues/3492)
- [ ] [record the norminated node for pod and consider it first in next cycle #3491](https://github.com/volcano-sh/volcano/issues/3491)

**Comment by Monokaix** [comment]
Issues also need to concern about volcano controller:
https://github.com/volcano-sh/volcano/issues/3601
https://github.com/volcano-sh/volcano/issues/3597

**Comment by Monokaix** [comment]
The related PRs paste before has been solved, and the new issue will be solved in the future.

**Comment by JesseStutler** [comment]
This issue has followed by #3852, moved out from v1.10 milestone
