### ISSUE TITLE
Usability Improvement

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#556]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

- [x] Add log-file parameters to all components (https://github.com/volcano-sh/volcano/issues/557)
- [ ] Build global configuration (https://github.com/volcano-sh/volcano/issues/555)
- [ ] Replace schedulerName with selector (https://github.com/volcano-sh/volcano/issues/554)
- [x] Update the parameter of `vc-admission` to start with `--` (https://github.com/volcano-sh/volcano/issues/553)
- [x] Remove kube-batch from help message of cli (https://github.com/volcano-sh/volcano/issues/551)
- [ ] Command line enhancement (https://github.com/volcano-sh/volcano/issues/530)
- [x] Update glog to klog (#562)
